const q = (id, track, competency, difficulty, prompt, options, answer, explanation, keywords = []) => ({
  id, track, competency, difficulty, prompt, options, answer, explanation, keywords,
})

export const diagnosticBank = [
  q('a-fractions-1', 'academic', 'Number sense', 'foundation', 'Which value is equivalent to 3/4?', ['0.25', '0.50', '0.75', '1.25'], 2, '3 ÷ 4 = 0.75.', ['math', 'fractions', 'algebra']),
  q('a-equations-1', 'academic', 'Algebraic reasoning', 'core', 'Solve: 3x + 5 = 20.', ['x = 3', 'x = 5', 'x = 8', 'x = 15'], 1, 'Subtract 5, then divide 15 by 3.', ['math', 'algebra', 'equations']),
  q('a-functions-1', 'academic', 'Functions', 'core', 'If f(x) = 2x² − 1, what is f(3)?', ['11', '15', '17', '35'], 2, '2(3²) − 1 = 18 − 1 = 17.', ['math', 'algebra', 'functions']),
  q('a-probability-1', 'academic', 'Probability', 'core', 'A fair coin is flipped twice. What is the probability of exactly one head?', ['1/4', '1/3', '1/2', '3/4'], 2, 'HT and TH are 2 of the 4 equally likely outcomes.', ['math', 'probability', 'statistics']),
  q('a-reading-1', 'academic', 'Evidence & inference', 'core', 'Which action best supports a claim in an analytical response?', ['Repeat the claim', 'Use specific evidence and explain its relevance', 'Add unrelated facts', 'Use the longest quotation available'], 1, 'Strong analysis connects specific evidence to the claim.', ['english', 'reading', 'language arts', 'writing']),
  q('a-science-1', 'academic', 'Scientific reasoning', 'core', 'Why is a control group useful in an experiment?', ['It guarantees the hypothesis is correct', 'It provides a comparison for the tested variable', 'It removes the need for repeated trials', 'It increases every measurement'], 1, 'A control gives a baseline for comparing the effect of the independent variable.', ['science', 'biology', 'chemistry', 'physics']),
  q('a-biology-1', 'academic', 'Biology foundations', 'core', 'Which organelle is primarily responsible for ATP production in eukaryotic cells?', ['Ribosome', 'Mitochondrion', 'Golgi apparatus', 'Nucleus'], 1, 'Mitochondria generate most cellular ATP through respiration.', ['biology', 'cells', 'ap biology']),
  q('a-chemistry-1', 'academic', 'Chemistry foundations', 'core', 'What does atomic number represent?', ['Neutrons only', 'Protons', 'Protons + neutrons', 'Valence electrons only'], 1, 'Atomic number is the number of protons in the nucleus.', ['chemistry', 'atoms']),
  q('a-physics-1', 'academic', 'Physics foundations', 'core', 'If velocity changes from 4 m/s to 10 m/s in 3 s, what is average acceleration?', ['2 m/s²', '3 m/s²', '4.7 m/s²', '14 m/s²'], 0, '(10 − 4) ÷ 3 = 2 m/s².', ['physics', 'motion', 'kinematics']),
  q('a-study-1', 'academic', 'Learning strategy', 'foundation', 'Which approach best checks whether you can retrieve learned material?', ['Re-reading notes repeatedly', 'Highlighting every sentence', 'Closing notes and answering practice questions', 'Watching the same video at higher speed'], 2, 'Retrieval practice directly tests whether knowledge can be recalled.', ['study', 'exam', 'learning']),
  q('i-complexity-1', 'interview', 'Algorithms', 'core', 'What is the average lookup complexity of a well-implemented hash table?', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 0, 'Hash tables are designed for average constant-time lookup.', ['software', 'swe', 'developer', 'algorithms', 'coding']),
  q('i-tree-1', 'interview', 'Data structures', 'core', 'Which traversal of a binary search tree yields sorted keys?', ['Preorder', 'Inorder', 'Postorder', 'Level order'], 1, 'Inorder traversal visits BST keys in sorted order.', ['software', 'swe', 'developer', 'tree', 'coding']),
  q('i-debug-1', 'interview', 'Debugging', 'core', 'A service suddenly shows higher latency after a deployment. What is the strongest first action?', ['Rewrite the service', 'Compare new vs previous deployment metrics and traces', 'Increase every timeout', 'Delete logs'], 1, 'Comparing before/after telemetry narrows the regression quickly.', ['software', 'sre', 'backend', 'debugging']),
  q('i-system-1', 'interview', 'System design', 'core', 'What is a common reason to add a cache in front of a database?', ['Guarantee perfect consistency', 'Reduce repeated read latency and database load', 'Eliminate all storage', 'Make every write synchronous'], 1, 'Caching commonly improves read latency and reduces origin load.', ['software', 'swe', 'backend', 'system design']),
  q('i-api-1', 'interview', 'API design', 'core', 'For a create operation in a REST API, which status is typically appropriate after successful resource creation?', ['200 only', '201', '301', '404'], 1, '201 Created is the conventional response for successful resource creation.', ['software', 'api', 'backend']),
  q('i-react-1', 'interview', 'Frontend', 'core', 'In React, why should list items usually have stable keys?', ['To change CSS automatically', 'To help reconciliation identify items across renders', 'To encrypt state', 'To force every component to remount'], 1, 'Stable keys help React match elements during reconciliation.', ['react', 'frontend', 'javascript']),
  q('i-js-1', 'interview', 'JavaScript', 'core', 'What does Promise.all do if one input promise rejects?', ['Always resolves with null', 'Rejects with that rejection', 'Retries automatically', 'Waits forever'], 1, 'Promise.all rejects when any input promise rejects.', ['javascript', 'node', 'frontend']),
  q('i-sql-1', 'interview', 'Data & SQL', 'core', 'Which database index property most directly helps a selective equality lookup?', ['It increases row size only', 'It can reduce rows scanned to find matching keys', 'It guarantees no deadlocks', 'It replaces backups'], 1, 'An appropriate index can narrow the search without scanning all rows.', ['sql', 'database', 'backend', 'data']),
  q('i-behavior-1', 'interview', 'Behavioral communication', 'foundation', 'In a STAR interview answer, what does the “R” represent?', ['Reason', 'Result', 'Review', 'Role'], 1, 'STAR stands for Situation, Task, Action, Result.', ['behavioral', 'leadership', 'communication']),
  q('i-priority-1', 'interview', 'Problem solving', 'core', 'During a coding interview, you identify a brute-force O(n²) solution and a likely O(n) approach. What is the best next step?', ['Code silently immediately', 'Explain the tradeoff and validate assumptions before implementing', 'Refuse the brute-force idea', 'Ask the interviewer to solve it'], 1, 'Communicating assumptions and tradeoffs shows structured problem solving.', ['coding', 'algorithms', 'communication']),
]

export const fallbackQuestions = {
  academic: diagnosticBank.filter((item) => item.track === 'academic'),
  interview: diagnosticBank.filter((item) => item.track === 'interview'),
}
